#!/bin/sh

advanced=''

if [ $1 == -a ]
then
	shift
	advanced='a'
fi

expanded=$1
players=$2

name=$expanded.$players$advanced

rm -f rftg.$name.out

for i in `seq 1 1000`
do
	if [ "$advanced" == a ]
	then
		./learner -e $1 -p $2 -f 100 -a >> rftg.$name.out
	else
		./learner -e $1 -p $2 -f 100 >> rftg.$name.out
	fi
	echo $i
done
